# ====================================================================================
# CONFIGURACIÓN DEL PROXY INVERSO (Nginx Alpine Docker)
# TFG ASIR - Encapsulación SSL y Redirección a Odoo Backend
# ====================================================================================

# 1. BLOQUE HTTP (Puerto 80)
# Su única función es atrapar despistes. Si un cliente entra por http://, lo manda a https://
server {
    listen 80;
    server_name erp.techsolutions.local;
    
    # Redirección permanente (Código 301) forzando esquema seguro
    return 301 https://$host$request_uri;
}

# 2. BLOQUE HTTPS (Puerto 443)
# El núcleo seguro. Aquí Nginx "da la cara" al cliente, desencripta el tráfico y se lo pasa en claro al contenedor Odoo.
server {
    listen 443 ssl;
    server_name erp.techsolutions.local;

    # ======================== CONFIGURACIÓN SSL/TLS ========================
    # Rutas dentro del contenedor (Nginx lee el volumen del host: ./certs)
    ssl_certificate /etc/ssl/certs_local/odoo-selfsigned.crt;
    ssl_certificate_key /etc/ssl/certs_local/odoo-selfsigned.key;
    
    # Afinamiento de Seguridad (Eliminar protocolos obsoletos vulnerables a ataques)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    # Usar algoritmos de cifrado potentes de grado A
    ssl_ciphers HIGH:!aNULL:!MD5;
    
    # =======================================================================

    # Logs de acceso (Útiles para el TFG para demostrar accesos)
    access_log /var/log/nginx/odoo_access.log;
    error_log /var/log/nginx/odoo_error.log;

    # Optimización de carga para las subidas de ERP (archivos adjuntos grandes en Odoo)
    client_max_body_size 100M;

    # ======================== PROXY PASS A ODOO ============================
    location / {
        # 'odoo-web' es el nombre del contenedor en el docker-compose.yml
        proxy_pass http://odoo-web:8069;
        
        # Opciones obligatorias para WebSockets (Chat en vivo de Odoo) y compatibilidad HTTP/1.1
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Reescritura de Cabeceras
        # Esto le dice a Odoo (que está oculto) cuál era la IP real del cliente que inició la conexión
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Tiempos de espera ampliados (Odoo a veces tarda al compilar informes pesados)
        proxy_read_timeout 720s;
        proxy_connect_timeout 720s;
        proxy_send_timeout 720s;
    }
}
